version: "3.2"

services:
  soroban:
    image: "samouraiwallet/dojo-soroban:${DOJO_SOROBAN_VERSION_TAG}"
    container_name: soroban
    build:
      context: ./soroban
    env_file:
      - ./.env
      - ./conf/docker-soroban.conf
    restart: always
    command: "/restart.sh"
    expose:
      - "4242"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      dojonet:
        ipv4_address: 172.28.1.9
