version: "3.2"

services:
  tunnel:
    image: "samouraiwallet/dojo-tunnel:${DOJO_TUNNEL_VERSION_TAG}"
    container_name: tunnel
    build:
      context: ./tunnel
    env_file:
      - ./.env
    restart: always
    command: "/home/node/tunnel/wait-for nginx:80 --timeout=720 -- /home/node/tunnel/wait-for tor:9050 --timeout=720 -- /home/node/tunnel/restart.js"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - nginx
      - tor
    networks:
      dojonet:
        ipv4_address: ${NET_DOJO_TUNNEL_IPV4}
